advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path("", views.IndexView.as_view()),
    path("basic_app/", include('basic_app.urls', namespace='basic_app')),
    path("admin/", admin.site.urls),
]

advcbv/basic_app/urls.py
from unicodedata import name
from django.urls import path, re_path
from . import views

app_name = 'basic_app'
urlpatterns = [
    path("", views.SchoolListView.as_view(), name='list'),
    re_path(r'^(?P<pk>\d+)', views.SchoolDetailView.as_view(), name='detail'),
    path("create/", views.SchoolCreateView.as_view(), name='create'),
    re_path(r'update/(?P<pk>\d+)', views.SchoolUpdateView.as_view(), name='update'),
    re_path(r'delete/(?P<pk>\d+)', views.SchoolDeleteView.as_view(), name='delete'),
]

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
  name = models.CharField(max_length=256)
  principal = models.CharField(max_length=256)
  location = models.CharField(max_length=256)
  def __str__(self):
    return self.name
  def get_absolute_url(self):
    return reverse("basic_app:detail", kwargs={'pk':self.pk})

class Student(models.Model):
  name = models.CharField(max_length=256)
  age = models.PositiveIntegerField()
  school = models.ForeignKey(School, on_delete=models.CASCADE, related_name='students')
  def __str__(self):
    return self.name
  

advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View, TemplateView, 
                                  ListView, DetailView,
                                  CreateView, UpdateView, DeleteView)
from . import models
from django.urls import reverse_lazy
# Create your views here.
class CBView(View):
  def get(self, request):
    return render(request, "index.html")
class IndexView(TemplateView):
  template_name = "index.html"
  def get_context_data(self,**kwargs):
    context = super().get_context_data(**kwargs)
    context["injected"] = "Basic Injection !"
    return context
class SchoolListView(ListView):
  context_object_name = 'schools'
  model = models.School
class SchoolDetailView(DetailView):
  context_object_name = 'school_detail'
  model = models.School
  template_name: 'basic_app/school_detail.html'
class SchoolCreateView(CreateView):
  # context_object_name = 'create_school'
  fields = ('name','principal','location')
  model = models.School
  # template_name: 'basic_app/school_form.html'
class SchoolUpdateView(UpdateView):
  # context_object_name = 'create_school'
  fields = ('name','principal')
  model = models.School
  # template_name: 'basic_app/school_form.html'
class SchoolDeleteView(DeleteView):
  # context_object_name = 'create_school'
  model = models.School
  # template_name: 'basic_app/school_form.html'
  success_url = reverse_lazy("basic_app:list")

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Static part</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-default">
    <ul class="nav navbar-nav">
      <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
      <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
      <li><a class="navbar-link" href="#"></a></li>
    </ul>
  </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
</body>
</html>

advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}

<h3>Are you sure the scholl {{school.name}} to be deleted ?</h3>
<form method="POST">
  {% csrf_token %}
  <a href="{% url 'basic_app:detail' pk=school.pk %}" class="btn">Cancel</a>
  <input type="submit" class="btn btn-danger" value="Delete"/>
</form>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to School Details !</h1>
  <h2><strong>School details:</strong></h2>
  <p>Name: {{school_detail.name}}</p>
  <p>Principal: {{school_detail.principal}}</p>
  <p>Location: {{school_detail.location}}</p>
  <h3>Students:</h3>
  {% for student in school_detail.students.all %}
  <p>{{student.name}} is {{student.age}} years old.</p>
  {% endfor %}
</div>
<div class='container'>
  <p>
    <a class="btn btn-primary" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a>
    <a class="btn btn-warning" href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a>
  </p>
</div>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}

<h1>
  {% if not form.instance.pk %}
  Create School
  {% else %}
  Update School
  {% endif %}
</h1>
<form method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" class="btn btn-primary" value="Submit"/>
</form>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}

<h1> School List</h1>
<ol>
  {% for school in schools %}
  <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
  {% endfor %}
</ol>

{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Static part</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-default">
    <ul class="nav navbar-nav">
      <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
      <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
      <li><a class="navbar-link" href="#">Other</a></li>
    </ul>
  </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
</body>
</html>

advcbv/templates/index.html
{% extends "base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1><strong>Home Page!</strong></h1>
</div>
{% endblock %}